"""Business services, re-exported so routers keep the old services.* call sites."""

from app.services.operations.audit import list_audit_logs, list_call_logs
from app.services.shared.common import mask_key
from app.services.interviews.eval import list_eval_runs, run_question_eval, run_score_eval
from app.services.interviews.interview import (
    answer_interview,
    current_question,
    abandon_interview,
    build_report,
    delete_interview,
    end_interview,
    finish_interview,
    get_interview,
    list_interviews,
    pending_answer_run_id,
    prepare_interview,
    regenerate_report,
    resume_or_start,
    schedule_report,
    start_report_worker,
    stop_report_worker,
    start_interview,
    find_interview_create_replay,
)
from app.services.materials.knowledge import (
    accept_material,
    delete_material,
    enqueue_material_id,
    get_material,
    list_materials,
    pending_material_ids,
    recall,
    start_material_worker,
)
from app.services.operations.overview import admin_overview
from app.services.operations.providers import (
    create_provider,
    delete_provider,
    list_providers,
    list_roles,
    ping_provider,
    probe_models,
    seed_providers,
    update_provider,
    update_role,
)
from app.services.chat.session import (
    begin_chat,
    clear_session,
    complete_chat_turn,
    create_session,
    delete_session,
    discard_redirect_turn,
    finish_chat,
    get_session,
    iter_turn_parts,
    prepare_chat_file,
    list_sessions,
    send_chat,
    send_chat_graph,
    route_chat,
    recover_chat_turn,
    staged_chat_retrieval_callbacks,
    validate_stream_answer,
    repair_stream_answer,
)

__all__ = [
    "accept_material",
    "admin_overview",
    "answer_interview",
    "pending_answer_run_id",
    "begin_chat",
    "clear_session",
    "complete_chat_turn",
    "create_provider",
    "create_session",
    "current_question",
    "delete_interview",
    "delete_material",
    "delete_provider",
    "delete_session",
    "discard_redirect_turn",
    "end_interview",
    "enqueue_material_id",
    "finish_chat",
    "get_interview",
    "get_material",
    "get_session",
    "iter_turn_parts",
    "prepare_chat_file",
    "list_audit_logs",
    "list_call_logs",
    "list_eval_runs",
    "list_interviews",
    "prepare_interview",
    "regenerate_report",
    "list_materials",
    "list_providers",
    "list_roles",
    "list_sessions",
    "mask_key",
    "pending_material_ids",
    "ping_provider",
    "probe_models",
    "recall",
    "resume_or_start",
    "run_question_eval",
    "run_score_eval",
    "schedule_report",
    "start_report_worker",
    "stop_report_worker",
    "seed_providers",
    "send_chat",
    "send_chat_graph",
    "route_chat",
    "recover_chat_turn",
    "staged_chat_retrieval_callbacks",
    "validate_stream_answer",
    "repair_stream_answer",
    "start_interview",
    "find_interview_create_replay",
    "start_material_worker",
    "update_provider",
    "update_role",
]
