import { useEffect, useRef } from "react";
import { Color, Mesh, Program, Renderer, Triangle } from "ogl";
import "./strands.css";
const MAX_STRANDS = 12;
const MAX_COLORS = 8;
const VERT = `#version 300 es
in vec2 position;
void main() { gl_Position = vec4(position, 0.0, 1.0); }
`;
const FRAG = `#version 300 es
precision highp float;
uniform float uTime; uniform vec2 uResolution; uniform vec3 uColors[${MAX_COLORS}]; uniform int uColorCount; uniform int uStrandCount; uniform float uSpeed; uniform float uAmplitude; uniform float uWaviness; uniform float uThickness; uniform float uGlow; uniform float uTaper; uniform float uSpread; uniform float uHueShift; uniform float uIntensity; uniform float uOpacity; uniform float uScale; uniform float uSaturation;
out vec4 fragColor; const float PI = 3.14159265;
vec3 spectrum(float t) { return 0.5 + 0.5 * cos(2.0 * PI * (t + vec3(0.00, 0.33, 0.67))); }
vec3 samplePalette(float t) { t = fract(t); float scaled = t * float(uColorCount); int idx = int(floor(scaled)); float blend = fract(scaled); int nextIdx = idx + 1; if (nextIdx >= uColorCount) nextIdx = 0; return mix(uColors[idx], uColors[nextIdx], blend); }
vec3 strandColor(float t) { return uColorCount > 0 ? samplePalette(t) : spectrum(t); }
void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * uResolution) / uResolution.y; uv /= max(uScale, 0.0001); float e = 0.06 + uIntensity * 0.94; float env = pow(max(cos(uv.x * PI * 1.3), 0.0), uTaper); vec3 col = vec3(0.0); for (int i = 0; i < ${MAX_STRANDS}; i++) { if (i >= uStrandCount) break; float fi = float(i); float ph = fi * 1.7 * uSpread; float freq = (2.0 + fi * 0.35) * uWaviness; float spd = 1.4 + fi * 1.2; float tt = uTime * uSpeed; float w = sin(uv.x * freq + tt * spd + ph) * 0.60 + sin(uv.x * freq * 1.1 - tt * spd * 0.7 + ph * 1.7) * 0.40; float amp = (0.1 + 0.02 * e) * env * uAmplitude; float y = w * amp; float d = abs(uv.y - y); float thick = (0.001 + 0.05 * e) * (0.35 + env) * uThickness; float g = thick / (d + thick * 0.45); g *= g; float h = fi / float(uStrandCount) + uv.x * 0.30 + uTime * 0.04 + uHueShift; col += strandColor(h) * g * env; } col *= 0.45 + 0.7 * e; col = 1.0 - exp(-col * uGlow); float gray = dot(col, vec3(0.2126, 0.7152, 0.0722)); col = max(mix(vec3(gray), col, uSaturation), 0.0); float lum = max(max(col.r, col.g), col.b); float alpha = clamp(lum, 0.0, 1.0) * uOpacity; fragColor = vec4(col * uOpacity, alpha); }
`;
type StrandsProps = { colors?: string[]; count?: number; speed?: number; amplitude?: number; waviness?: number; thickness?: number; glow?: number; taper?: number; spread?: number; hueShift?: number; intensity?: number; saturation?: number; opacity?: number; scale?: number; glass?: boolean; className?: string; style?: React.CSSProperties };
const buildPalette = (colors: string[] = []) => { const filled = colors.length ? colors : ["#ffffff"]; return Array.from({ length: MAX_COLORS }, (_, i) => { const c = new Color(filled[i] ?? filled[filled.length - 1]); return [c.r, c.g, c.b]; }); };
/** WebGL shader renderer for the luminous additive voice strands. */
export default function Strands({ colors = ["#FF4242", "#7C3AED", "#06B6D4", "#EAB308"], count = 3, speed = 0.5, amplitude = 1, waviness = 1, thickness = 0.7, glow = 2.6, taper = 3, spread = 1, hueShift = 0, intensity = 0.6, saturation = 1.5, opacity = 1, scale = 1.5, glass = false, className = "", style }: StrandsProps) {
  const containerRef = useRef<HTMLDivElement>(null); const propsRef = useRef<StrandsProps>({}); propsRef.current = { colors, count, speed, amplitude, waviness, thickness, glow, taper, spread, hueShift, intensity, saturation, opacity, scale, glass };
  useEffect(() => { const container = containerRef.current; if (!container) return; const renderer = new Renderer({ alpha: true, premultipliedAlpha: true, antialias: true }); const gl = renderer.gl; gl.clearColor(0, 0, 0, 0); gl.enable(gl.BLEND); gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA); const geometry = new Triangle(gl); if (geometry.attributes.uv) delete geometry.attributes.uv; const initial = propsRef.current; const uniforms = { uTime: { value: 0 }, uResolution: { value: [1, 1] }, uColors: { value: buildPalette(initial.colors) }, uColorCount: { value: Math.min(initial.colors?.length || 0, MAX_COLORS) }, uStrandCount: { value: Math.min(initial.count || 3, MAX_STRANDS) }, uSpeed: { value: initial.speed }, uAmplitude: { value: initial.amplitude }, uWaviness: { value: initial.waviness }, uThickness: { value: initial.thickness }, uGlow: { value: initial.glow }, uTaper: { value: initial.taper }, uSpread: { value: initial.spread }, uHueShift: { value: initial.hueShift }, uIntensity: { value: initial.intensity }, uOpacity: { value: initial.opacity }, uScale: { value: initial.scale }, uSaturation: { value: initial.saturation } }; const program = new Program(gl, { vertex: VERT, fragment: FRAG, uniforms }); const mesh = new Mesh(gl, { geometry, program }); container.appendChild(gl.canvas); const resize = () => { const width = container.offsetWidth; const height = container.offsetHeight; renderer.setSize(width, height); program.uniforms.uResolution.value = [width, height]; }; resize(); window.addEventListener("resize", resize); let frame = 0; const render = (time: number) => { frame = requestAnimationFrame(render); const current = propsRef.current; program.uniforms.uTime.value = time * 0.001; program.uniforms.uColors.value = buildPalette(current.colors); program.uniforms.uColorCount.value = Math.min(current.colors?.length || 0, MAX_COLORS); program.uniforms.uStrandCount.value = Math.min(Math.max(Math.round(current.count || 3), 1), MAX_STRANDS); program.uniforms.uSpeed.value = current.speed; program.uniforms.uAmplitude.value = current.amplitude; program.uniforms.uWaviness.value = current.waviness; program.uniforms.uThickness.value = current.thickness; program.uniforms.uGlow.value = current.glow; program.uniforms.uTaper.value = current.taper; program.uniforms.uSpread.value = current.spread; program.uniforms.uHueShift.value = current.hueShift; program.uniforms.uIntensity.value = current.intensity; program.uniforms.uOpacity.value = current.opacity; program.uniforms.uScale.value = current.scale; program.uniforms.uSaturation.value = current.saturation; renderer.render({ scene: mesh }); }; frame = requestAnimationFrame(render); return () => { cancelAnimationFrame(frame); window.removeEventListener("resize", resize); gl.canvas.remove(); gl.getExtension("WEBGL_lose_context")?.loseContext(); }; }, []);
  return <div ref={containerRef} className={`strands-container ${className}`} style={style} />;
}
